name: Microsoft Graph TypeScript Typings Build_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - master
  paths:
    include:
    - index.d.ts

pool:
  vmImage: 'ubuntu-latest'

variables:
  newVersionStr: ""
steps:
# test artifact
- task: CopyFiles@2
  displayName: 'Copy Files to staging directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
     **/*
     !node_modules/**/*
     !scripts/node_modules/**/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: YodLabs.O365PostMessage.O365PostMessageBuild.O365PostMessageBuild@0
  displayName: 'Graph Client Tooling pipeline fail notification'
  inputs:
    addressType: serviceEndpoint
    serviceEndpointName: 'microsoftgraph pipeline status'
    title: '$(Build.DefinitionName) failure notification'
    text: 'This automated pipeline has failed. View the build details for further information. This is a blocking failure.'
  condition: and(failed(), ne(variables['Build.Reason'], 'Manual')) # Only notify if the automated build failed.
  enabled: true